// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOX57qhSiS3OgANI1p_zlhIhrREAIJ06k',
    appId: '1:19730816384:web:80169a5aa43c2d99efb565',
    messagingSenderId: '19730816384',
    projectId: 'todoappproject-c53f3',
    authDomain: 'todoappproject-c53f3.firebaseapp.com',
    storageBucket: 'todoappproject-c53f3.firebasestorage.app',
    measurementId: 'G-JSZZSQ5SX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZ7ATjd86CVVOjBM2ttxY-GSrhgH3O0c',
    appId: '1:19730816384:android:f301cf80398707ffefb565',
    messagingSenderId: '19730816384',
    projectId: 'todoappproject-c53f3',
    storageBucket: 'todoappproject-c53f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBKP2lVC6NIPST9s1b9El1Cc0WrOFtO_g',
    appId: '1:19730816384:ios:41ee289fc6c43874efb565',
    messagingSenderId: '19730816384',
    projectId: 'todoappproject-c53f3',
    storageBucket: 'todoappproject-c53f3.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBKP2lVC6NIPST9s1b9El1Cc0WrOFtO_g',
    appId: '1:19730816384:ios:41ee289fc6c43874efb565',
    messagingSenderId: '19730816384',
    projectId: 'todoappproject-c53f3',
    storageBucket: 'todoappproject-c53f3.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOX57qhSiS3OgANI1p_zlhIhrREAIJ06k',
    appId: '1:19730816384:web:bee370ad78ca8150efb565',
    messagingSenderId: '19730816384',
    projectId: 'todoappproject-c53f3',
    authDomain: 'todoappproject-c53f3.firebaseapp.com',
    storageBucket: 'todoappproject-c53f3.firebasestorage.app',
    measurementId: 'G-N6EKV448J4',
  );
}
